### ISSUE TITLE
Verbingung zum mqtt Server bricht nach exact 5min ab

### ISSUE THREAD

**Issue by powo01** [ReverseEngineeringDE/SAIC-API-Documentation#40]
Hallo,

erstmal vielen Dank für diese Software. Leider wird anscheindet die MQTT Verbindung zu meinem MQTT Server nach 5min getrennt

java.util.concurrent.ExecutionException: Client is not connected (32104)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at net.heberling.ismart.mqtt.SaicMqttGateway.call(SaicMqttGateway.java:293)
	at net.heberling.ismart.mqtt.SaicMqttGateway.call(SaicMqttGateway.java:67)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at net.heberling.ismart.mqtt.SaicMqttGateway.main(SaicMqttGateway.java:327)
	Suppressed: Client is disconnected (32101)
		at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
		at org.eclipse.paho.client.mqttv3.internal.ClientComms.disconnect(ClientComms.java:507)
		at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:818)
		at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:779)
		at org.eclipse.paho.client.mqttv3.MqttAsyncClient.disconnect(MqttAsyncClient.java:788)
		at org.eclipse.paho.client.mqttv3.MqttClient.disconnect(MqttClient.java:347)
		at net.heberling.ismart.mqtt.SaicMqttGateway$1.close(SaicMqttGateway.java:176)
		at net.heberling.ismart.mqtt.SaicMqttGateway.call(SaicMqttGateway.java:172)
		... 10 more
Caused by: Client is not connected (32104)
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:205)
	at org.eclipse.paho.client.mqttv3.MqttAsyncClient.publish(MqttAsyncClient.java:1375)
	at org.eclipse.paho.client.mqttv3.MqttClient.publish(MqttClient.java:570)
	at net.heberling.ismart.mqtt.VehicleHandler.updateChargeStatus(VehicleHandler.java:549)
	at net.heberling.ismart.mqtt.VehicleHandler.handleVehicle(VehicleHandler.java:79)
	at net.heberling.ismart.mqtt.SaicMqttGateway.lambda$call$2(SaicMqttGateway.java:278)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
Mit Wireshark sind die letzten Lebenszeichen

das der Server ein Websocket PING schickt und der Client darauf sofort die Verbindung schliesst

**Comment by powo01** [comment]
Nachtrag, Wireshark log

No.	Time	Source	Destination	Protocol	Length	Info
24336	2927.427581	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [FIN, ACK] Seq=198 Ack=3493852 Win=64128 Len=0 TSval=3719584148 TSecr=342776726
24335	2927.427565	192.168.16.253	192.168.16.71	WebSocket	72	WebSocket Connection Close [FIN] 
24334	2927.427502	192.168.16.71	192.168.16.253	TCP	66	34128 → 1884 [FIN, ACK] Seq=3493851 Ack=192 Win=64512 Len=0 TSval=342776726 TSecr=3719584146
24333	2927.427490	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=192 Ack=3493851 Win=64128 Len=0 TSval=3719584148 TSecr=342776726
24329	2926.824223	192.168.16.71	192.168.16.253	WebSocket	126	WebSocket Binary [FIN] [MASKED]
24330	2926.868076	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493841 Win=64128 Len=0 TSval=3719583589 TSecr=342776123
24331	2927.425542	192.168.16.253	192.168.16.71	WebSocket	68	WebSocket Ping [FIN] 
24332	2927.427470	192.168.16.71	192.168.16.253	WebSocket	76	WebSocket Connection Close [FIN] [MASKED]
24328	2926.824104	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493781 Win=64128 Len=0 TSval=3719583545 TSecr=342776123
24327	2926.824076	192.168.16.71	192.168.16.253	WebSocket	118	WebSocket Binary [FIN] [MASKED]
24325	2926.823760	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493665 Win=64128 Len=0 TSval=3719583544 TSecr=342776122
24326	2926.823915	192.168.16.71	192.168.16.253	WebSocket	130	WebSocket Binary [FIN] [MASKED]

**Comment by powo01** [comment]
Nachtrag Wireshark Log
No.	Time	Source	Destination	Protocol	Length	Info
24322	2926.823352	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493559 Win=64128 Len=0 TSval=3719583544 TSecr=342776122
24323	2926.823570	192.168.16.71	192.168.16.253	WebSocket	117	WebSocket Binary [FIN] [MASKED]
24324	2926.823732	192.168.16.71	192.168.16.253	WebSocket	121	WebSocket Binary [FIN] [MASKED]
24325	2926.823760	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493665 Win=64128 Len=0 TSval=3719583544 TSecr=342776122
24326	2926.823915	192.168.16.71	192.168.16.253	WebSocket	130	WebSocket Binary [FIN] [MASKED]
24327	2926.824076	192.168.16.71	192.168.16.253	WebSocket	118	WebSocket Binary [FIN] [MASKED]
24328	2926.824104	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493781 Win=64128 Len=0 TSval=3719583545 TSecr=342776123
24329	2926.824223	192.168.16.71	192.168.16.253	WebSocket	126	WebSocket Binary [FIN] [MASKED]
24330	2926.868076	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=190 Ack=3493841 Win=64128 Len=0 TSval=3719583589 TSecr=342776123
24331	2927.425542	192.168.16.253	192.168.16.71	WebSocket	68	WebSocket Ping [FIN] 
24332	2927.427470	192.168.16.71	192.168.16.253	WebSocket	76	WebSocket Connection Close [FIN] [MASKED]
24333	2927.427490	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [ACK] Seq=192 Ack=3493851 Win=64128 Len=0 TSval=3719584148 TSecr=342776726
24334	2927.427502	192.168.16.71	192.168.16.253	TCP	66	34128 → 1884 [FIN, ACK] Seq=3493851 Ack=192 Win=64512 Len=0 TSval=342776726 TSecr=3719584146
24335	2927.427565	192.168.16.253	192.168.16.71	WebSocket	72	WebSocket Connection Close [FIN] 
24336	2927.427581	192.168.16.253	192.168.16.71	TCP	66	1884 → 34128 [FIN, ACK] Seq=198 Ack=3493852 Win=64128 Len=0 TSval=3719584148 TSecr=342776726
24337	2927.427675	192.168.16.71	192.168.16.253	TCP	60	34128 → 1884 [RST] Seq=3493852 Win=0 Len=0
24338	2927.427700	192.168.16.71	192.168.16.253	TCP	60	34128 → 1884 [RST] Seq=3493852 Win=0 Len=0

**Comment by tisoft** [comment]
Sehr komisch. Automatic reconnect ist an, der sollte sich einfach neu verbinden...

Ich mache bei mir MQTT über TCP und nicht über WebSockets, kannst du mal probieren, ob es bei direkter TCP Verbindung (Standardmässig Port 1883) funktioniert?

**Comment by tisoft** [comment]
Könnte https://github.com/eclipse/paho.mqtt.java/issues/960 sein.

**Comment by powo01** [comment]
mit Verbindungstyp tcp:// an Stelle von ws:// scheint es zu gehen. Mein Mosqiutto Server hier ist die Distributionsversion von Debiab Bullseye. Vielen Dank für den schnellen Support

**Comment by tisoft** [comment]
Ich lasse den mal offen, das sollte ja auch mit ws:// funktionieren.

**Comment by tisoft** [comment]
Ja, websocket mit bestimmten mosquitto Versionen ist kaputt. Ist der Fehler https://github.com/eclipse/paho.mqtt.java/issues/960. Scheint aber niemanden dort zu interessieren...

tcp://mqtt-server:1883 sollte gehen.

**Comment by tisoft** [comment]
We have splitted this project up in several subprojects under the https://github.com/SAIC-iSmart-API organization.

Please open a thread in the discussions over there, if your question/issue is still unsolved: https://github.com/orgs/SAIC-iSmart-API/discussions
